Task 2. Regex to DFA
DavidBykov/formal-lang-course pull request #2
Opened 2021-09-14 13:44 UTC by DavidBykov

- [X] Используя возможности [pyformlang](https://pyformlang.readthedocs.io/en/latest/) реализовать **функцию** построения минимального ДКА по заданному регулярному выражению. [Формат регулярного выражения.](https://pyformlang.readthedocs.io/en/latest/usage.html#regular-expression).
- [X] Добавить необходимые тесты.

2021-09-14 16:20 UTC, EgorOrachyov requested changes

2021-09-14 16:20 UTC, EgorOrachyov commented on project/regex.py
> +from pyformlang.finite_automaton import DeterministicFiniteAutomaton
`pyformlang` надо добавить в `requirements.txt`, если его там еще нет

2021-09-14 16:20 UTC, EgorOrachyov commented on tests/test_regex.py
> +    assert dfa.is_deterministic()
напрашивается на самом деле несколько отдельных тестов:
- детерминированный
- минимальный ? (сравнить с каким-то ожидаемым известным числом состояний)
- эквивалентный и тд

2021-09-14 16:20 UTC, EgorOrachyov commented on tests/test_regex.py
> +def test_regex_to_dfa_accept(
Идея хорошая, но читать данную конструкцию с множеством вложенных списков затруднительно.
Предлагаю обойтись без этой аннотации (как и в других местах - там ведь тоже нет) и переделать в обычном стиле

2021-09-14 16:20 UTC, EgorOrachyov commented on tests/test_regex.py
> +        assert not dfa.accepts(unexpected_word)
Немного не понятно, зачем смотреть на то, что `unexpected`, тк ожидаем только 1 результат. Предлагаю только 1 ассерт оставить

2021-09-14 16:20 UTC, EgorOrachyov commented on tests/test_regex.py
> +    regex = "1 1 (1 0)*"
Достаточно простое выражение, хотелось бы еще вариантов (не обязательно с большим алфавитом), но со звездой Клини и альтернативой

2021-09-15 17:26 UTC, DavidBykov commented on project/regex.py
> +from pyformlang.finite_automaton import DeterministicFiniteAutomaton
Done

2021-09-15 17:27 UTC, DavidBykov commented on tests/test_regex.py
> +    assert dfa.is_deterministic()
Проверка на минимальность и эквивалентность есть в следующем тесте

2021-09-15 17:27 UTC, DavidBykov commented on tests/test_regex.py
> +def test_regex_to_dfa_accept(
Done

2021-09-15 17:27 UTC, DavidBykov commented on tests/test_regex.py
> +        assert not dfa.accepts(unexpected_word)
Я убрал, но вообще не совсем понятно, почему не нужно проверять unexpected, ведь нужно проверить, что он не пропускает слова, которые не нужны.

2021-09-15 17:27 UTC, DavidBykov commented on tests/test_regex.py
> +    regex = "1 1 (1 0)*"
Done

2021-09-16 09:56 UTC, EgorOrachyov commented on tests/test_regex.py
> +        assert not dfa.accepts(unexpected_word)
Теперь понятно, какая идея была с unexpected.

2021-09-16 09:57 UTC, EgorOrachyov approved these changes

2021-09-16 13:30 UTC, merged